# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
# realizo dos yml para separar el que tiene el fly token, con el de CICD. 
name: Fly Deploy
on:
  push:
    branches:
      - deploy-actions
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKENS }}
